[package]
name = "philosophers_table"
version = "0.1.0"
edition = "2021"

[dependencies]

# Random number generator for time between state changes
rand = "0.8.5"

# CLI argument handling
clap = { version = "4.*", features = ["derive"] }